services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      $bundleConfig: '%huh_entity_approval%'

  HeimrichHannot\EntityApprovalBundle\:
    resource: "../../{DataContainer,EventListener,EventSubscriber,Manager}/*"