services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      $bundleConfig: '%huh_entity_approvement%'

  HeimrichHannot\EntityApprovementBundle\EventListener\Contao\LoadDataContainerListener: ~

  HeimrichHannot\EntityApprovementBundle\Manager\:
    resource: ../../Manager/*

  HeimrichHannot\EntityApprovementBundle\DataContainer\:
    resource: ../../DataContainer/*