framework:
  workflows:
    entity_approval:
      type: 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: 'single_state'
        arguments:
          - 'huh_approval_state'
      supports:
        - Contao\Model
      initial_marking: created
      places:
        - created
        - approved
        - rejected
        - in_audit
      transitions:
        submit:
          from: created
          to: in_audit
        assign_new_auditor:
          from: in_audit
          to: in_audit
        approve:
          from: in_audit
          to: approved
        reject:
          from: in_audit
          to: rejected
        request_change:
          from: in_audit
          to: created