framework:
  workflows:
    entity_approval:
      type: 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: 'single_state'
        arguments:
          - 'huhApproval_state'
      supports:
        - Contao\Model
      initial_marking: wait_for_initial_auditor
      places:
        - created
        - wait_for_initial_auditor
        - in_progress
        - changes_requested
        - approved
        - rejected
      transitions:
        assign_initial_auditor:
          from: created
          to: wait_for_initial_auditor
        assign_auditor:
          from: wait_for_initial_auditor
          to: in_progress
        remove_all_auditors:
          from: in_progress
          to: wait_for_initial_auditor
        approve:
          from: in_progress
          to: approved
        reject:
          from: in_progress
          to: rejected
        request_change:
          from: [in_progress, rejected, approved]
          to: changes_requested
        apply_change:
          from: changes_requested
          to: in_progress


